version: "3.3"
services:
  db:
    image: mongo:${MONGODB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ../src/ui
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${HOST_PORT}:9292/tcp
    networks:
      - front_net
  post:
    build: ../src/post-py
    image: ${USER_NAME}/post:${POST_VERSION}
    links:
      - db:post_db
    networks:
      - front_net
      - back_net

  comment:
    build: ../src/comment
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    links:
      - db:comment_db
    networks:
      - front_net
      - back_net

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
      ipam:
        config:
          - subnet: 10.0.1.0/24
