version: "3.3"
services:
  db:
    image: mongo:${MONGODB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${REPONAME}/ui:${UI_VERSION}
    ports:
      - ${HOST_PORT}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${REPONAME}/post:${POST_VERSION}
    links:
      - db:post_db
    networks:
      - front_net
      - back_net

  comment:
    build: ./comment
    image: ${REPONAME}/comment:${COMMENT_VERSION}
    links:
      - db:comment_db
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
      ipam:
        config:
          - subnet: 10.0.1.0/24
